# Site wide configuration

title:            Summer School on Visualization & Virtual Characters For Computer Games
locale:           en_US
url:              https://kthsummerschool.github.io
urlcolor: blue

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  #enable_coderay: false


# Site owner
owner:
  name: "KTH & ANIMATAS"
  avatar: "/assets/images/KTHLogo.png"
  bio: "KTH Summer school on visualization and virtual characters for computer games"
  email: cpeters@kth.se
  disqus-shortname:

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
